language: ruby
rvm:
  - 2.3.1
bundler_args: --without development
script: bundle exec rails db:create db:schema:load db:migrate test
services:
  - postgresql
addons:
  postgresql: "9.5"
before_script:
  - cp config/database.yml.travis config/database.yml
